language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
os:
  - linux
#  - osx
#  - windows
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install --upgrade importlib_metadata; fi
  - pip install coveralls coverage flake8
  - python setup.py install
before_script:
  # Break build in case of serious syntax errors or missing imports
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
script: coverage run --include bdbag/*,bdbag/fetch/* --omit bdbag/bdbag_cli.py,bdbag/bdbag_ro.py,bdbag/bdbagit_profile.py,bdbag/fetch/transports/fetch_globus.py,bdbag/fetch/transports/fetch_boto3.py setup.py test
after_success: coveralls
after_failure:
  - cat test.log
  - cat test_cli.log
