language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
#  - osx
#  - windows
install:
  - pip install python-coveralls coverage
  - python setup.py install
script: coverage run --include bdbag/*,bdbag/fetch/* --omit bdbag/bdbag_cli.py,bdbag/bdbag_ro.py,bdbag/bdbagit_profile.py,bdbag/fetch/transports/fetch_globus.py,bdbag/fetch/transports/fetch_boto3.py setup.py test
after_success: coveralls
after_failure:
  - cat test.log
  - cat test_cli.log
